/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HotsTeamRouteImport } from './routes/hots-team'

const HotsTeamRoute = HotsTeamRouteImport.update({
  id: '/hots-team',
  path: '/hots-team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/hots-team': typeof HotsTeamRoute
}
export interface FileRoutesByTo {
  '/hots-team': typeof HotsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/hots-team': typeof HotsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/hots-team'
  fileRoutesByTo: FileRoutesByTo
  to: '/hots-team'
  id: '__root__' | '/hots-team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HotsTeamRoute: typeof HotsTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hots-team': {
      id: '/hots-team'
      path: '/hots-team'
      fullPath: '/hots-team'
      preLoaderRoute: typeof HotsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HotsTeamRoute: HotsTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
